name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build_plugins
      run:  python CI/build_plugins.py
    - name: commit changes
      run:  | 
       git remote set-url origin ${{ secrets.ssh }}
       git add .
       git commit -m "plugins build"
       git push origin master
